In [49]:
import torch
import numpy as np

In [66]:
trial = np.random.random()
trial

0.8233542117491429

In [ ]:
num_sources = 1
source_probs = np.arrray([1])

In [ ]:
trial = np.random.random()

        s = 0
        # here self.num_sources =1 
        for i in range(num_sources):
            # here self.source_probs = [1]
            if (trial >= s) and (trial <= s + source_probs[i]):
                print("got triggered")
                bin_len = len(self.source_smiles[i])
                sm = self.source_smiles[i][idx % bin_len]

                props = self.source_props[i][idx % bin_len]
                miss = self.source_missings[i][idx % bin_len]

                if self.with_missings:
                    return sm, torch.concat([props, miss])
                else:
                    return sm, props
            # so our x here is a SMILE string
            s += self.source_probs[i]

In [51]:
d = torch.rand((3, 3), device='cuda', requires_grad=True)

In [57]:
??print

In [58]:
print("2", end="")
print("3")

23


In [54]:
e = d**2

In [59]:
xs = torch.rand((5, 3, 64, 64))
ys = torch.rand((5, 1000))
dataset = torch.utils.data.TensorDataset(xs, ys)

In [65]:
dataset[2][1].shape

torch.Size([1000])

In [56]:
e.tolist()

[[0.023216886445879936, 0.22621478140354156, 0.30526620149612427],
 [0.5416929125785828, 0.4030209183692932, 0.004151985980570316],
 [0.6864627003669739, 0.05315402150154114, 0.7332966327667236]]

In [2]:
a = torch.arange(10).reshape(5,2)
a

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [6]:
torch.split(a, 1, dim=1)

(tensor([[0],
         [2],
         [4],
         [6],
         [8]]),
 tensor([[1],
         [3],
         [5],
         [7],
         [9]]))

In [18]:
c = torch.tensor([4, 5])
c.numpy()

array([4, 5])

In [14]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

In [30]:
f = a.to('cuda')

In [34]:
print(f)

tensor([2., 3.], device='cuda:0', grad_fn=<CopyBackwards>)


In [29]:
a.device

device(type='cpu')

In [15]:
Q = 3*a**3 - b**2

In [19]:
Q.detach().numpy()

array([-12.,  65.], dtype=float32)

In [20]:
a.device

device(type='cpu')

In [21]:
t = torch.tensor([4, 53])
t_n = t.numpy()

In [22]:
t[0] = 23
t

tensor([23, 53])

In [23]:
t_n

array([23, 53])